root: true
env:
  react-native/react-native: true
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - "@typescript-eslint"
  - react
  - react-hooks
  - react-native
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:react-native/all
  - prettier
reportUnusedDisableDirectives: true
rules:
  "@typescript-eslint/no-unused-vars":
    - warn
    - argsIgnorePattern: ^_
      ignoreRestSiblings: true
  react/react-in-jsx-scope: off
  react-native/split-platform-components: off # A-ToDo only supports Android version
