name: build preview

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.18
          cache: yarn
      - uses: expo/expo-github-action@v8
        with:
          eas-version: ^3.14.0
          token: ${{ secrets.EXPO_TOKEN }}
      - run: yarn --frozen-lockfile
      - run: yarn build
